In [2]:
import numpy as np
z = np.zeros([2, 3])
print(z.shape)

(2, 3)


In [2]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
(np.zeros(5)).shape

(5,)

In [ ]:
result = [ [3, 3, 4], [2, 4, 4], [5, 5, 0], [6, 4, 0] ]
result = np.array(result)
[i, j] = np.where(result == 0)  # 回傳 0 的位址。i = [2, 3] (2 個零所在的列數)，j = [2, 2] (2 個零所在的行數)
# result = np.delete(result, i, axis = 0)
# result
i, j

(array([2, 3]), array([2, 2]))

In [22]:
a = np.array([[0, 2, 4]])
b = np.array([1, 1, 1, 1, 1, 1, 1, 1])
b[a] += 1
b

array([2, 1, 2, 1, 2, 1, 1, 1])

In [27]:
a = np.array([[1], [2], [3]])
a = a.reshape(-1, 1)[0]
a

array([1])

In [38]:
# 有三個 User，每個 User 有一個空間大小為 2 的 Queue
Buffer = np.array([[2, 3, 4], [1, 6, 7]])  # shape = (2, 3)
k = np.sum(Buffer, axis = 0)  # k = array([3, 9, 11])
l = np.where(k != 0)  # output : array([0, 1, 2])
# 代表 3 個 UE 的 Queue 都有東西
k


array([ 3,  9, 11])

In [39]:
a = np.zeros([2, 3])
a[:, 0].size

2

In [1]:
import torch
import torch.version
torch.cuda.is_available(), torch.version.cuda, torch.cuda.get_device_name(0)

(True, '12.8', 'NVIDIA GeForce RTX 5070 Ti')

In [ ]:
import os
if not os.path.exists("./saved_agents/GANDDQN"):
    os.makedirs("./saved_agents/GANDDQN")
    print("done")
else: print("already exsists")

done


In [3]:
import torch
a = torch.tensor(1).to(torch.float)
a.dtype

torch.float32

In [5]:
input = torch.tensor([
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  # sample 0
    [[20, 21, 22], [23, 24, 25], [26, 27, 28]]   # sample 1
])  # shape: (2, 3, 3)  # (batch_size=2, num_actions=3, num_samples=3)

index = torch.tensor([
    [[2, 0, 1]],  # sample 0: want action 2 at sample 0, action 0 at sample 1, ...
    [[1, 1, 0]]   # sample 1: ...
])  # shape: (2, 1, 3)

result = input.gather(1, index)  # dim = 1 → 在 action 維度選

result, result.shape

(tensor([[[16, 11, 15]],
 
         [[23, 24, 22]]]),
 torch.Size([2, 1, 3]))

In [2]:
import itertools
import numpy as np
# 回傳一個 WGAN-GP 的 Action Space : list
def action_space(total, num):  # total = 10 (total_band = 10MHz)，num = 3 (3 types of NS)
    tmp = list(itertools.product(range(total + 1), repeat=num))  # itertools.product() : 產出所有 0~10 中取 3 個數字的所有組合。將 (x, y, z) 存入 tmp
    result = []
    # 從一堆 (x, y, z) 中挑出 x + y + z = 10 的組合存入 result
    for value in tmp:  # 
        if sum(value) == total:
            result.append(list(value))
    result = np.array(result)
    
    [i, j] = np.where(result == 0)  # 找出 result 中那些 [x, y, z] 其中任一為 0 的組合。
    result = np.delete(result, i, axis=0)  # 刪除那些任一為 0 的組合
    # example : 
    # result = [ [3, 3, 4], [2, 4, 4], [5, 5, 0], [6, 4, 0] ]
    # result = np.array(result)
    # np.where(result == 0)
    # return : (array([2, 3]), array([2, 2]))  # 回傳 0 的位址。i = [2, 3] (2 個零所在的列數)，j = [2, 2] (2 個零所在的行數)
    # print(result.shape)

    return result  # x + y + z = 10，且任一不為 0

action_space(10, 3).shape

(36, 3)

In [3]:
len((1, 2, 3))

3

In [ ]:
a = np.array([1, 2, 3])
np.zeros(a.shape)

# if a.shape == (3,):
#     print("yes")


(3,)

In [ ]:
reward = 0
if type(reward) == : print("yes")
else: print("no")


no


In [28]:
memory = [([1, 2, 3], 5, 6, [4, 5, 6]), ([1, 3, 4], 7, 8, (10, 11, 12))]
np.random.shuffle(memory)
memory

[([1, 3, 4], 7, 8, (10, 11, 12)), ([1, 2, 3], 5, 6, [4, 5, 6])]

In [11]:
import numpy as np

def moving_average(data, window_size):
    data = np.array(data)
    return np.convolve(data, np.ones(window_size) / window_size, mode='valid')

In [13]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
window_size = 3

ma = moving_average(data, window_size)
ma, data  # 輸出: array([2., 3., 4., 5., 6., 7., 8., 9.])

(array([2., 3., 4., 5., 6., 7., 8., 9.]), [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [9]:
import torch
a = torch.tensor([[1], [2], [3]])
a.reshape(-1, 1)
a.shape

torch.Size([3, 1])

In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = (a + 1).reshape(-1, 1)

a.shape, b, b.shape

((3,),
 array([[2],
        [3],
        [4]]),
 (3, 1))

In [16]:
a = np.random.normal(0, 8, 10).reshape(-1, 1)
b = a.reshape(-1, 1)[0]
b

array([-3.77811977])