In [1]:
import numpy as np
z = np.zeros([2, 3])
print(z.shape)

(2, 3)


In [2]:
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
(np.zeros(5)).shape

(5,)

In [ ]:
result = [ [3, 3, 4], [2, 4, 4], [5, 5, 0], [6, 4, 0] ]
result = np.array(result)
[i, j] = np.where(result == 0)  # 回傳 0 的位址。i = [2, 3] (2 個零所在的列數)，j = [2, 2] (2 個零所在的行數)
# result = np.delete(result, i, axis = 0)
# result
i, j

(array([2, 3]), array([2, 2]))

In [22]:
a = np.array([[0, 2, 4]])
b = np.array([1, 1, 1, 1, 1, 1, 1, 1])
b[a] += 1
b

array([2, 1, 2, 1, 2, 1, 1, 1])

In [27]:
a = np.array([[1], [2], [3]])
a = a.reshape(-1, 1)[0]
a

array([1])

In [38]:
# 有三個 User，每個 User 有一個空間大小為 2 的 Queue
Buffer = np.array([[2, 3, 4], [1, 6, 7]])  # shape = (2, 3)
k = np.sum(Buffer, axis = 0)  # k = array([3, 9, 11])
l = np.where(k != 0)  # output : array([0, 1, 2])
# 代表 3 個 UE 的 Queue 都有東西
k


array([ 3,  9, 11])

In [39]:
a = np.zeros([2, 3])
a[:, 0].size

2